config/routes.rb
Madlibris::Application.routes.draw do

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }

  resources :madlibris_games  
  root to: "home#index"
  post 'madlibris_games', to: 'madlibris_games#create_game', as: "create_madlibris_game"
  get 'madlibris_display', to: "madlibris_games#options_display", as: 'options_display'
  get 'madlibris_game_view', to: 'madlibris_games#game_view', as: "play_madlibris_game"
  post 'choose_book', to: 'madlibris_games#choose_book', as: "choose_madlibris_book"
  post 'accept_invite', to: 'madlibris_games#accept_invite', as: "accept_invitation"
  post 'reject_invite', to: 'madlibris_games#reject_invite', as: "reject_invitation"
  post 'uninvite', to: 'madlibris_games#uninvite', as: "uninvite_user"
  get 'new_first_line/:id', to: 'madlibris_games#new_line', as: "new_first_line"
  post 'write_first_line', to: 'madlibris_games#write_line', as: "write_line"
  get 'new_line_choice/:id', to: 'madlibris_games#new_line_choice', as: "new_line_choice"
  post 'make_line_choice', to: 'madlibris_games#choose_line', as: "choose_line"
  post 'send_invite', to: 'madlibris_games#send_invite', as: "send_invite"

end

app/models/madlibris_game.rb
class MadlibrisGame < Game
  # validate :has_multi_players?

  def choosing_book?
    truth_array = rounds.select { |r| r.book_choosing? }
    truth_array.include?(true)
  end
  
  def invited_users
    users = outstanding_invites.collect { |gu| gu.user }
  end

  def book_chooser?(user)
    chooser = latest_round.try(:book_chooser)
    user == chooser
  end

  def book_choice_pending?
    latest_round.book_choice.pending?
  end

  def needs_to_choose_book?(user)
    book_chooser?(user) && book_choice_pending? && playing?
  end

  def line_chooser?(user)
    line_choosers = latest_round.try(:line_choosers)
    if line_choosers
      line_choosers.include?(user)
    end
  end

  def line_writing?
    latest_round.first_line_writing?
  end

  def needs_to_write_line?(user)
    line_chooser?(user) && line_writing? && user.get_first_line(latest_round).try(:pending?)
  end

  def line_choosing?
    latest_round.line_choosing?
  end

  def needs_to_choose_line?(user)
    line_chooser?(user) && line_choosing? && user.get_line_choice(latest_round).try(:pending?)
  end

  def self.invite_usernames_to_game(usernames_array, game_host)
    new_game = game_host.new_game("multi-player")[0]
    confirmed_invites = [ ]
    usernames_array.each { |username|
      if user = User.find_by_username(username)
        game_host.invite_existing_user(user, new_game)
        confirmed_invites << username
      end
    }
    game_host.notifications.create(text: "#{confirmed_invites.join(", ")} were successfully invited to the game}")
    new_game
  end

  def game_host
    games_users.collect { |gu| gu.user if gu.user_role == "host" }.compact[0]
  end

  def progress_game
    if new_round_needed?
      build_round_models
    else
      complete
    end
  end

  def new_round_needed?
    not_enough_rounds? || any_incomplete_rounds?
  end

  def not_enough_rounds?
    rounds.length < games_users.length
  end

  def any_incomplete_rounds?
    incomplete_rounds = rounds.select { |r| r.completed? == false }
    incomplete_rounds.any?
  end
  
  def ready_to_play?
    if enough_players? && no_outstanding_invites? && no_invites_to_send?
      true
    else
      false
    end
  end

  def accepted_games_users
    games_users.select { |games_user| games_user.try(:accepted?) }
  end

  def enough_players?
    players = accepted_games_users
    if players
      players.length >= 3
    else
      false
    end
  end

  def latest_round
    rounds.sort_by { |r| r.created_at }.last
  end



  def no_invites_to_send?
    games_users.select { |games_user| games_user.try(:to_do?) } == [ ]
  end

  def build_round_models
      round = self.rounds.create
      book_choice = round.build_book_choice
      [round, book_choice]
  end

  def host
    games_users
  end

  def current_score
    game_score_hash = zero_points_hash
    if completed_rounds.any?
      completed_rounds.each { |round|
        game_score_hash = add_round_to_current_score(game_score_hash, round.current_score)
      }
    end
    game_score_hash
  end

  def formatted_score
    formatted_hash = { }
    current_score.each { |gu_id, points|
      formatted_hash[gu_id] = [GamesUser.username(gu_id), points ]
    }
    formatted_hash
  end

  def add_round_to_current_score(round_hash, current_score_hash)
    game_user_ids = round_hash.keys.sort
    raise "error compiling score" unless game_user_ids == current_score_hash.keys.sort
      game_user_ids.each { |id|
        current_score_hash[id] = current_score_hash[id] + round_hash[id]
      }
    current_score_hash
  end

  def zero_points_hash
    hash = { }
    games_users.accepteds.each {
        |gu|
        hash[gu.id] = 0
    }
    hash
  end

  def completed_rounds
    rounds.select { |round| round.completed?}
  end

  def book_choice_made?
    if rounds.first
      rounds.first.book_choice.completed?
    else
      false
    end
  end



# need to be amended to accomodate game creation process, right now will blow it up
  def has_multi_players?
    if self.kind == 'multi-player'
      errors.add(:base, "A multi-player Madlibris Game must have at least three players.") unless self.users.length >= 3
    end
  end
end

app/controllers/madlibris_games_controller.rb
class MadlibrisGamesController < ApplicationController
  load_and_authorize_resource

  def options_display
    @user = current_user || @user
    @current_games = current_user.ongoing_madlibris_games
    @pending_invites = current_user.invited_madlibris_games
    @notifications = current_user.notifications
    @game = MadlibrisGame.new
    render action: "options_display"
  end

  def create
    usernames = [ ]
    usernames << params[:username1] << params[:username2] << params[:username3] << params[:username4] << params[:username5] 
    @user = current_user || @user
    @game = MadlibrisGame.invite_usernames_to_game(usernames, @user)
    @books = Book.game_view(@game, @user)
    redirect_to(options_display_path)
  end

  def show
    @user = current_user
    @game = MadlibrisGame.find(params[:id])
    @books = Book.game_view(@game, @user)
    render :show, :layout => "game_layout"
  end

  def choose_book
    @user = current_user
    @game = MadlibrisGame.find(params[:game_id])
    @book = Book.find(params[:book_id])
    @round = @game.latest_round
    @user.choose_book(@round, @book)
    redirect_to(options_display_path)
  end

  def new_line
    @user = current_user
    @game = MadlibrisGame.find(params[:id])
    @books = Book.game_view(@game, @user)
    render :new_line, :layout => "game_layout"
  end

  def write_line
    @user = current_user
    @round = Round.find(params[:round_id])
    @text = params[:text]
    @first_line = @user.draft_first_line(@round, @text)
    if @first_line.written?
      flash[:notice] = "Line submitted."
    else
      flash[:alert] = "uh-oh, something went wrong."
    end
    redirect_to(options_display_path)
  end

  def new_line_choice
    @user = current_user
    @game = MadlibrisGame.find(params[:id])
    @round = @game.latest_round
    @books = Book.game_view(@game, @user)
  end

  def choose_line
    @user = current_user
    @round = Round.find(params[:round_id])
    @first_line = FirstLine.find(params[:first_line_id])
    @line_choice = @user.choose_first_line(@round, @first_line)
    if @line_choice.selected_true_line?
      flash[:notice] = "Correct: you get +1 points."
    elsif @line_choice.selected_true_line? == false
      flash[:alert] = "#{@line_choice.author_username} wrote that. #{@line_choice.author_username} gets +2 points."
    else

    end
    redirect_to(options_display_path)
  end

  def accept_invite
    @user = current_user
    @game = MadlibrisGame.find(params[:game_id])
    @games_user = @user.accept_invitation(@game)
    if @games_user.accepted?
      flash[:notice] = "Invitation Accepted"
    else
      flash[:alert] = "Uh-oh. Something went wrong."
    end
    redirect_to(options_display_path)
  end

  def reject_invite
    @user = current_user
    @game = MadlibrisGame.find(params[:game_id])
    @games_user = @user.reject_invitation(@game)
    if @games_user.rejected?
      flash[:alert] = "You declined the invitation."
    else
      flash[:alert] = "Uh-oh. Something went wrong."
    end

    redirect_to(options_display_path)
  end

  def uninvite
    @user = current_user
    @uninvited_user = User.find_by_username(params[:username])
    @game = MadlibrisGame.find(params[:game_id])
    @result = @user.uninvite_from_game(@uninvited_user, @game)

    respond_to do |format|
      format.json { render :json => { user: @uninvited_user.username, game: @game.id, result: @result } }
    end
  end

  def send_invite
    @user = current_user
    if @invited_user = User.find_by_username(params[:username])
      @game = MadlibrisGame.find(params[:game_id])
      @game = @user.invite_existing_user(@invited_user, @game)[0]
      @result = true
    else
      @result = false
    end
    respond_to do |format|
      format.json { render :json => { game: @game.id, username: @invited_user.username, result: @result } }
    end
  end

end

app/helpers/madlibris_games_helper.rb
module MadlibrisGamesHelper

  def display_authors(book)
    names = book.authors.collect { |author| author.name }
    names.to_sentence
  end

  def display_game_info(user, game)
    link_to list_opponent_usernames(game, user), determine_game_url(game, user), class: "button expand #{link_class(user, game)}"
  end

  def list_opponent_usernames(game, user)
    games_users = (game.outstanding_invites << game.accepted_games_users).flatten
    user_names = games_users.collect { |gu| gu.user.username if gu.user.username != user.username }.compact
    opponents = user_names.join(" ") + " " + determine_message(game, user)
  end

  def opponents_array(game, user)
    games_users = (game.outstanding_invites << game.accepted_games_users).flatten
    user_names = games_users.collect { |gu| gu.user.username if gu.user.username != user.username }.compact
  end

  def determine_game_url(game, user)
    if game.needs_to_choose_book?(user)
      madlibris_game_path(game.id)
    elsif game.needs_to_write_line?(user)
      new_first_line_path(game.id)
    elsif game.needs_to_choose_line?(user)
      new_line_choice_path(game.id)
    else
      ""
    end
  end

  def determine_message(game, user)
    if game.needs_to_choose_book?(user) && game.rounds.try(:length) == 1
      "Choose Book to Start Game"
    elsif game.latest_round.try(:book_choosing?) && game.latest_round.try(:book_chooser) != user
      "Awaiting Book Choice"
    elsif game.needs_to_choose_book?(user)
      "Choose Book"
    elsif (game.latest_round.try(:first_line_writing?) && game.latest_round.try(:book_chooser) == user) || (game.latest_round.try(:first_line_writing?) && user.first_line_written?(game))
      "Awaiting Opponents' First Lines"
    elsif game.needs_to_write_line?(user)
      "Draft Line"
    elsif game.latest_round.try(:line_choosing?) && game.latest_round.try(:book_chooser) == user || (game.latest_round.try(:line_choosing?) && user.line_choosing?(game))
      "Awaiting Opponents Line Choices"
    elsif game.needs_to_choose_line?(user)
      "Pick Line"
    else
      "Awaiting Invite Responses"
    end
  end

  def link_class(user, game)
    classes = [ ]
    if list_opponent_usernames(game, user) == ""
    end
    if (game.game_host.id == user.id && game.proposing?) || game.playing?
      classes << "split" 
    end
    classes << "disabled" unless activate_button?(game, user)
    classes.join(" ")
  end

  def activate_button?(game, user)
    if game.needs_to_choose_book?(user) || game.needs_to_write_line?(user) || game.needs_to_choose_line?(user)
      true
    else
      
    end
  end

end

app/views/madlibris_games/_book.html.haml
.book-container
  .row
    .small-12.medium-8.small-centered.columns.text-center
      = image_tag(book.image_url, class: "book-image")
  .row
    .small-12.medium-8.small-centered.columns.text-center
      %h2  
        = "#{book.title}"
  .row
    .small-12.medium-8.small-centered.columns.text-center      
      %h2.subheader
        = "by #{display_authors(book)}"
  .row
    .small-12.medium-8.small-centered.columns.text-center
      %h3.subheader book description:
      %p.text-justify
        = book.synopsis

app/views/madlibris_games/_uninvite_button.html.haml
= form_tag(uninvite_user_path) do |f|
  = hidden_field_tag(:game_id, game.id)
  = hidden_field_tag(:user_id, user.id)
  = submit_tag "#{user.username}", class: "button tiny alert"

app/views/madlibris_games/new_line.html.haml
= render partial: "book", locals: {book: @books}
.row
  .small-12.medium-8.large-6.small-centered.columns
    = form_tag(write_line_path) do |f|
      = text_area_tag(:text, nil, placeholder: "Write here what you think is the first sentence of the book.  If you trick other players into thinking this sentence is the real first sentence of the book, you get points!")
      = hidden_field_tag(:round_id, @game.latest_round.id)
      = submit_tag "submit", class: "button expand"

app/views/madlibris_games/new_line_choice.html.haml
= render partial: "book", locals: {book: @books}
- @books.introductory_content.other_lines.each do |ol|
  .row
    .small-12.medium-8.large-6.small-centered.columns.text-center
      %h3
        = ol.text
= form_tag(choose_line_path) do |f|
  .row
    .small-12.medium-8.large-6.small-centered.columns.text-center
      %p Which line is really the first line of the book?
      - @round.all_first_lines.each do |fl|
        - if fl.user_id != current_user.id
          .row
            .small-1.left
              = radio_button_tag :first_line_id, fl.id
            .small-11.text-left.right
              = "#{fl.text}"
            
  .row
    .small-12.medium-8.large-6.small-centered.columns
      = hidden_field_tag(:round_id, @game.latest_round.id)
      = submit_tag "submit", class: "button expand"

app/views/madlibris_games/options_display.html.haml
%dl.accordion{"data-accordion" => "", class: "small-12 medium-8 large-6 small-centered columns" }
  %dd
    = link_to "Create New Game", '#invite'
    #invite.content
      = form_tag(create_madlibris_game_path) do |f|
        %p Challenge Opponenets  (min 2):
        = text_field_tag :username1, nil, placeholder: "madlibris username"
        = text_field_tag :username2, nil, placeholder: "madlibris username"
        and add more (optional): 
        = text_field_tag :username3
        = text_field_tag :username4
        = text_field_tag :username5
        = submit_tag "Send Invitations", class: "button medium"
    %dd
      = link_to "Current Games", '#current_games'
      #current_games.content.active{data_current_games: @current_games.length}
        - if @current_games.any?
          - @current_games.each do |game|
            .row
              - if current_user.host?(game) == true && game.book_choice_made? == false
                .small-12.columns
                  = link_to determine_game_url(game, current_user), class: "expand button #{link_class(current_user, game)}", id: "game#{game.id}" do
                    = list_opponent_usernames(game, current_user)
                    %span{"data-dropdown" => "drop#{game.id}"}
                  %ul.f-dropdown{id: "drop#{game.id}", "data-dropdown-content" => "", "data-game_id" => game.id}
                    - opponents_array(game, current_user).each do |opponent|
                      %li{class: "drop#{game.id}"}
                        .small-6.columns
                          %p.opponent
                            = opponent
                        .small-6.columns.text-right 
                          %p.uninvite{"data-game_id" => game.id, "data-username" => opponent} x
                    %li  
                      %a{href: "", id: "additional_player"} add another player
        - if @current_games.any?
          - @current_games.each do |game|
            - if current_user.host?(game) == false && game.book_choice_made? == false
              .row   
                .small-12.columns
                  = display_game_info(current_user, game) 
            
            - if game.book_choice_made?
              .row
                .small-12.columns
                  = link_to determine_game_url(game, current_user), class: "expand button #{link_class(current_user, game)}", id: "game#{game.id}" do
                    = list_opponent_usernames(game, current_user)
                    %span{"data-dropdown" => "drop#{game.id}"}
                  %ul.f-dropdown{id: "drop#{game.id}", "data-dropdown-content" => "", "data-game_id" => game.id}
                    - game.formatted_score.each do |gu_id, score_array| 
                      %li
                        %a 
                          = "#{score_array[0]}: #{score_array[1]}"
    - if @pending_invites.any?
      %dd
        = link_to "Game Invitations", '#pending_invites'
        #pending_invites.content{data_invites: @pending_invites.length}
          %p Invitations from: 
          - @pending_invites.each do |game|
            .row
              .small-3.medium-4.columns
                %p 
                  = game.game_host.username
              .small-4.columns
                = form_tag(accept_invitation_path) do |f|
                  = hidden_field_tag(:game_id, game.id)
                  = submit_tag "Accept", class: "button small"
              .small-4.columns
                = form_tag(reject_invitation_path) do |f|
                  = hidden_field_tag(:game_id, game.id)
                  = submit_tag "Reject", class: "button small"
- javascript_include_tag('options_display.js')

 

app/views/madlibris_games/show.html.haml
.single-item
  - @books.each do |book|
    .book-container
      .row
        .small-12.medium-8.small-centered.columns.text-center
          = image_tag(book.image_url, class: "book-image")
      .row
        .small-12.medium-8.small-centered.columns.text-center      
          = form_tag(choose_madlibris_book_path) do |f|
            = hidden_field_tag :book_id, book.id
            = hidden_field_tag :game_id, @game.id 
            = submit_tag "select book", class: "button small"
      .row
        .small-12.medium-8.small-centered.columns.text-center
          .h1 
            = book.title
      .row
        .small-12.medium-8.small-centered.columns.text-center      
          .h1.subheader
            = display_authors(book)
      .row
        .small-12.medium-8.small-centered.columns.text-center
          .p.text-justify
            = book.synopsis
- javascript_include_tag('book_choice.js')